---
- hosts: all
  become: yes
  user: root
  gather_facts: yes
  tasks:
    - name: common
      include_role:
        name: common

    - name: docker installation
      include_role:
        name: docker

    - name: database
      include_role:
        name: database
      when: inventory_hostname in groups['mainapp']

    - name: webhook
      include_role:
        name: webhook
      when: inventory_hostname in groups['mainapp']

    - name: go application
      include_role:
        name: goapplication
      when: inventory_hostname in groups['mainapp']
    
    - name: Kubernetes 
      include_role:
        name: k8s
    
    - name: argocd
      include_role:
        name: argocd
      when: inventory_hostname in groups['master']
