---
- name: Create Application directory
  file:
    path: /home/ubuntu/PaaSeasy
    state: directory

- name: GET webhook binary file from Github release
  get_url:
    url: https://github.com/amirianos/PaasEasy/releases/download/v1.0.0/webhook
    dest: /home/ubuntu/PaaSeasy
    mode: 0777

- name: Create Service
  template:
    src: webhook.service.j2
    dest: /etc/systemd/system/webhook.service
    owner: root
    mode: 0400

- name: start webhook service
  service:
    name: webhook
    state: started
