---
- name: GET Golang application binary file from Github release
  get_url:
    url: https://github.com/amirianos/PaasEasy/releases/download/v1.0.6/paaseasy.zip
    dest: /home/ubuntu/

- name: Creates directory
  file:
    path: /home/ubuntu/goapp
    state: directory

- name: unzip downloaded file
  shell: unzip /home/ubuntu/paaseasy.zip -d /home/ubuntu/goapp

- name: Create Service
  template:
    src: goapplication.service.j2
    dest: /etc/systemd/system/goapplication.service
    owner: root
    mode: 0400

- name: start application service
  service:
    name: goapplication
    state: started

- name: start webhook service for load new config files 
  service:
    name: webhook
    state: restarted

